apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    tier: frontend
    app: gke
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
      - containerPort: 90
