apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: my-app
        image: 787367675716.dkr.ecr.ap-south-1.amazonaws.com/ssk-ecr-repo:latest
        ports:
        - containerPort: 80
