apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    app2: nginx2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
