apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    appname: voting-app
spec:
  replicas: 4
  template:
    metadata:
      name: voting-app
      labels:
        type: vote
    spec:
      containers:
        - name: my-ngi-con
          image: nginx:latest
          
