apiVersion: v1
kind: ReplicationController
metadata:
  name: argo-rs
spec:
  replicas: 4
  selector:
    app: argo
  template:
    metadata:
      name: argo
      labels:
        tier: frontend
    spec:
      containers:
        - name: myapp-nginx
          image: nginx:latest
